[versions]
accompanistPermissions = "0.37.3"
agp = "8.13.0" # see https://developer.android.com/studio/releases/gradle-plugin
androidxActivity = "1.11.0"
androidxBiometric = "1.1.0"
androidxComposeMaterialIconsExtended = "1.7.8"
androidxComposeMaterial = "1.9.4"
androidxComposeMaterial3 = "1.4.0"
androidxComposeMaterial3Adaptive = "1.2.0"
androidxComposeMaterial3AdaptiveNavigationSuite = "1.4.0"
androidxComposeUi = "1.9.4"
androidxCoreSplashscreen = "1.2.0"
androidxDatastorePreferences = "1.1.7"
androidxHilt = "1.3.0"
androidxLifecycle = "2.9.4"
androidxMedia3 = "1.8.0"
androidxNavigation = "2.9.6"
androidxTestExtJunit = "1.3.0"
androidxTestRunner = "1.7.0"
arturboschDetekt = "1.23.8"
autonomousappsDependencyAnalysis = "3.4.1"
benManesVersions = "0.53.0"
coil = "2.7.0"
dagger = "2.57.2"
googleAndroidMaterial = "1.13.0"
googleAndroidPlayAppUpdate = "2.1.0"
junitBom = "6.0.1"
kotlin = "2.2.21" # see https://developer.android.com/jetpack/androidx/releases/compose-kotlin
kotlinxDatetime = "0.7.1"
kotlinxSerializationJson = "1.9.0"
ksp = "2.3.0"
ktor = "3.3.1"
touchlabKermit = "2.0.8"
tripletPlay = "3.12.1"
undercouchDownload = "5.6.0"
wajahatkarimFlippable = "1.5.4"

[plugins]
android-application-plugin = { id = "com.android.application", version.ref = "agp" }
arturbosch-detekt-plugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "arturboschDetekt" }
autonomousapps-dependency-analysis-plugin = { id = "com.autonomousapps.dependency-analysis", version.ref = "autonomousappsDependencyAnalysis" }
ben-manes-versions-plugin = { id = "com.github.ben-manes.versions", version.ref = "benManesVersions" } # ./gradlew dependencyUpdates -Drevision=release
dagger-hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-android-plugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-plugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
triplet-play-plugin = { id = "com.github.triplet.play", version.ref = "tripletPlay" }
undercouch-download-plugin = { id = "de.undercouch.download", version.ref = "undercouchDownload" }

[libraries]
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "androidxBiometric" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "androidxComposeMaterial" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "androidxComposeMaterialIconsExtended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "androidxComposeMaterial3AdaptiveNavigationSuite" }
androidx-compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "androidxComposeMaterial3" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidxComposeUi" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastorePreferences" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHilt" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-media3-cast = { group = "androidx.media3", name = "media3-cast", version.ref = "androidxMedia3" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidxMedia3" }
androidx-media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "androidxMedia3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "androidxMedia3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExtJunit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
google-android-material = { group = "com.google.android.material", name = "material", version.ref = "googleAndroidMaterial" } # https://github.com/material-components/material-components-android/releases
google-android-play-app-update = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "googleAndroidPlayAppUpdate" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junitBom" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-resources = { group = "io.ktor", name = "ktor-client-resources", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
touchlab-kermit = { group = "co.touchlab", name = "kermit", version.ref = "touchlabKermit" }
wajahatkarim-flippable = { group = "com.wajahatkarim", name = "flippable", version.ref = "wajahatkarimFlippable" } # https://devlibrary.withgoogle.com/products/android/repos/wajahatkarim3-Flippable
